[theme]
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = true

[server]
maxUploadSize = 200
enableXsrfProtection = true